export const USER_LOGIN = "USER_LOGIN";
export const USER_LOGIN_SUCCESS = "USER_LOGIN_SUCCESS";
export const USER_LOGIN_ERROR = "USER_LOGIN_ERROR";

export const USER_LOGOUT = "USER_LOGOUT";
export const USER_LOGOUT_SUCCESS = "USER_LOGOUT_SUCCESS";
export const USER_LOGOUT_ERROR = "USER_LOGOUT_ERROR";

export const CREATE_ORDER = "CREATE_ORDER";
export const CREATE_ORDER_SUCCESS = "CREATE_ORDER_SUCCESS";
export const CREATE_ORDER_ERROR = "CREATE_ORDER_ERROR";

export const GET_ORDERS_FILTERIC = "GET_ORDERS_FILTERIC";
export const GET_ORDERS_FILTERIC_SUCCESS = "GET_ORDERS_FILTERIC_SUCCESS";
export const GET_ORDERS_FILTERIC_ERROR = "GET_ORDERS_FILTERIC_ERROR";

export const CHANGE_ORDER_STATUS = "CHANGE_ORDER_STATUS";
export const CHANGE_ORDER_STATUS_SUCCESS = "CHANGE_ORDER_STATUS_SUCCESS";
export const CHANGE_ORDER_STATUS_ERROR = "CHANGE_ORDER_STATUS_ERROR";

export const EDIT_ORDER = "EDIT_ORDER"
export const UPDATE_ORDER = "UPDATE_ORDER";
export const UPDATE_ORDER_SUCCESS = "UPDATE_ORDER_SUCCESS";
export const UPDATE_ORDER_ERROR = "UPDATE_ORDER_ERROR";

export const DELETE_ORDER = "DELETE_ORDER";
export const DELETE_ORDER_SUCCESS = "DELETE_ORDER_SUCCESS";
export const DELETE_ORDER_ERROR = "DELETE_ORDER_ERROR";

export const PAY_ORDER = "PAY_ORDER";
export const PAY_ORDER_SUCCESS = "PAY_ORDER_SUCCESS";
export const PAY_ORDER_ERROR = "PAY_ORDER_ERROR";

export const GET_ALL_CUSTOMER = "GET_ALL_CUSTOMER";
export const GET_ALL_CUSTOMER_SUCCESS = "GET_ALL_CUSTOMER_SUCCESS";
export const GET_ALL_CUSTOMER_ERROR = "GET_ALL_CUSTOMER_ERROR";

export const LOAD_CUSTOMER_LIST = "LOAD_CUSTOMER_LIST";
export const LOAD_CUSTOMER_SUCCESS = "LOAD_CUSTOMER_SUCCESS";
export const LOAD_CUSTOMER_FAIL = "LOAD_CUSTOMER_FAIL";

export const ADD_CUSTOMER = "ADD_CUSTOMER";
export const ADD_CUSTOMER_SUCCESS = "ADD_CUSTOMER_SUCCESS";
export const ADD_CUSTOMER_FAIL = "ADD_CUSTOMER_FAIL";
export const UPDATE_CUSTOMER_SUCCESS = "UPDATE_CUSTOMER_SUCCESS";

export const EDIT_CUSTOMER = "EDIT_CUSTOMER";
export const EDIT_CUSTOMER_SUCCESS = "EDIT_CUSTOMER_SUCCESS";
export const EDIT_CUSTOMER_FAIL = "EDIT_CUSTOMER_FAIL";

export const LOAD_CUSTOMER_GROUP = "LOAD_CUSTOMER_GROUP";
export const LOAD_CUSTOMER_GROUP_SUCCESS = "LOAD_CUSTOMER_GROUP_SUCCESS";
export const LOAD_CUSTOMER_GROUP_FAIL = "LOAD_CUSTOMER_GROUP_FAIL";

export const DELETE_CUSTOMER = "DELETE_CUSTOMER";
export const DELETE_CUSTOMER_FAIL = "DELETE_CUSTOMER_FAIL";

export const GET_ALL_CUSTOMERS = "GET_ALL_CUSTOMERS";
export const ORDER_PAYMENT = "ORDER_PAYMENT";